import type { Metadata } from "next";
import { Roboto, Mulish } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const roboto = Roboto({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const mulish = Mulish({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "900",
});

export const metadata: Metadata = {
  title: "CareFirst Third Party Booking",
  description: "Third party booking system for CareFirst clients and their units",
  icons: {
    // Multi-format icon set generated by realfavicongenerator (files in /public).
    // Order matters: the .ico goes first as the universal fallback (esp. for
    // Firefox / older browsers that request /favicon.ico by URL convention),
    // followed by explicitly-sized PNGs for modern browsers that read sizes.
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon-32x32.png", type: "image/png", sizes: "32x32" },
      { url: "/favicon-16x16.png", type: "image/png", sizes: "16x16" },
    ],
    shortcut: "/favicon.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${mulish.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
